---

- hosts: worker
  vars_files:
    - vars_hosts_info.yml

  tasks:
  - name: Set hostname from inventory
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Add host IP to /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ item.net_ip }}  {{ item.hostname }} {{ item.fqdn }}"
      regexp: "^{{ item.net_ip }}\\s"
    loop: "{{ tnodes }}"

