---

- hosts: all

  roles:
    - role: my-role
      service_title: "Httpd Web"
    - role: my-role2
  tasks:
    - name: Print finish role play
      ansible.builtin.debug:
        msg: "Finish role play"

