---

- hosts: localhost

  tasks:
    - name: Print supported os
      ansible.builtin.debug:
        msg: >
             OS Type: {{ ansible_facts['distribution'] }}
             OS Version: {{ ansible_facts['distribution_version'] }}
      when: 
        - ansible_facts['distribution'] == "Rocky"
        - ansible_facts['distribution_version'] == "8.10" 
